name: Multi Search and Replace

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      phrases:
        description: 'Comma-separated list of search and replace pairs (search1|replace1,search2|replace2)'
        required: true
        default: 'old_phrase1|new_phrase1,old_phrase2|new_phrase2'

permissions:
  contents: write  # Grant write permissions to the repository contents

jobs:
  search_and_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Search and replace phrases in .html files and commit changes
        env:
          PHRASES: ${{ github.event.inputs.phrases }}
        run: |
          IFS=',' read -ra PAIRS <<< "$PHRASES"
          for PAIR in "${PAIRS[@]}"; do
              IFS='|' read -ra TERMS <<< "$PAIR"
              SEARCH_PHRASE=${TERMS[0]}
              REPLACE_PHRASE=${TERMS[1]}
              ESCAPED_SEARCH=$(printf '%s\n' "${SEARCH_PHRASE}" | sed 's:[\/&]:\\&:g')
              ESCAPED_REPLACE=$(printf '%s\n' "${REPLACE_PHRASE}" | sed 's:[\/&]:\\&:g')
              find . -name "*.html" -type f -exec sed -i "s|${ESCAPED_SEARCH}|${ESCAPED_REPLACE}|g" {} +
          done

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          DATE=$(date +'%Y-%m-%d')
          git add .
          git commit -m "Applied multiple search and replace operations on ${DATE}"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main
