name: Search and Replace

on:
  push:
    branches:
      - main  # or any branch you want to listen to

jobs:
  search_and_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Search and replace phrase in .html files and commit changes
        env:
          SEARCH_PHRASE: "old_phrase"  # Set your old phrase here
          REPLACE_PHRASE: "new_phrase"  # Set your new phrase here
        run: |
          find . -name "*.html" -type f -exec sed -i "s/${SEARCH_PHRASE}/${REPLACE_PHRASE}/g" {} +
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          DATE=$(date +'%Y-%m-%d')
          git add .
          git commit -m "change ${SEARCH_PHRASE} to ${REPLACE_PHRASE} on ${DATE}"
          git push
